name: SimpleSanction
main: fr.fewerelk.simplesanction.SimpleSanction
author: fewerelk
version: 1.0
dependecies: #none
api-version: 1.19
commands:
  sanction:
    permission: simplesanction.sanction
    description: Sanction a player